### PR TITLE
feat: add globmatch

### PR DESCRIPTION
**Pull request by feloraaa**
Signed-off-by: feloraaa <704596810@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@xiaobeiswift plz review

**Comment by hsluoyz** [comment]
@feloraaa why close?

**Comment by feloraaa** [comment]
> @feloraaa why close?

The code wasn't uploaded correctly, I will retry again.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casbin/SwiftCasbin/pull/25

**Pull request closed without merging**
